/**
 * Dữ liệu mẫu cho cửa hàng điện tử & phụ kiện. Tách riêng để seed.ts chỉ lo phần logic.
 *
 * Lưu ý về tên miền email: mọi tài khoản mẫu dùng @example.com, là tên miền được
 * RFC 2606 dành riêng cho tài liệu và ví dụ. KHÔNG dùng .local, .test hay
 * .localhost — đó là các TLD dành riêng cho mục đích đặc biệt, bị pgAdmin và
 * phần lớn dịch vụ SMTP từ chối, nên luồng gửi email ở Phase 3 sẽ không chạy.
 * Cũng không dùng tên miền có thật, vì email thử nghiệm có thể bay tới người lạ.
 */

export const PERMISSIONS: Array<[string, string]> = [
  ['user:read', 'Xem danh sách và chi tiết người dùng'],
  ['user:create', 'Tạo người dùng'],
  ['user:update', 'Sửa thông tin người dùng'],
  ['user:delete', 'Xoá mềm người dùng'],
  ['user:assign_role', 'Cấp hoặc đổi quyền của người dùng'],
  ['product:read', 'Xem sản phẩm ở khu vực quản trị'],
  ['product:create', 'Tạo sản phẩm'],
  ['product:update', 'Sửa sản phẩm'],
  ['product:delete', 'Xoá mềm sản phẩm'],
  ['category:read', 'Xem danh mục ở khu vực quản trị'],
  ['category:create', 'Tạo danh mục'],
  ['category:update', 'Sửa danh mục'],
  ['category:delete', 'Xoá mềm danh mục'],
  ['order:read_all', 'Xem mọi đơn hàng của mọi khách'],
  ['order:update_status', 'Chuyển trạng thái đơn hàng'],
  ['order:cancel', 'Huỷ đơn hàng của khách'],
  ['inventory:read', 'Xem tồn kho'],
  ['inventory:adjust', 'Nhập kho, xuất kho, điều chỉnh tồn'],
  ['coupon:read', 'Xem mã giảm giá'],
  ['coupon:create', 'Tạo mã giảm giá'],
  ['coupon:update', 'Sửa mã giảm giá'],
  ['coupon:delete', 'Xoá mã giảm giá'],
  ['review:moderate', 'Ẩn hoặc hiện đánh giá'],
  ['audit:read', 'Xem nhật ký thao tác'],
  ['dashboard:view', 'Xem dashboard quản trị'],
];

/** ADMIN nhận toàn bộ quyền nên không liệt kê ở đây. */
export const STAFF_PERMISSIONS = [
  'user:read',
  'product:read',
  'category:read',
  'order:read_all',
  'order:update_status',
  'order:cancel',
  'inventory:read',
  'inventory:adjust',
  'coupon:read',
  'dashboard:view',
];

export const CATEGORY_TREE: Array<{ name: string; children: string[] }> = [
  { name: 'Bàn phím', children: ['Bàn phím cơ', 'Bàn phím không dây'] },
  { name: 'Chuột', children: ['Chuột gaming', 'Chuột văn phòng'] },
  { name: 'Tai nghe', children: ['Tai nghe chụp tai', 'Tai nghe nhét tai'] },
  { name: 'Màn hình', children: ['Màn hình gaming', 'Màn hình đồ hoạ'] },
  { name: 'Lưu trữ', children: ['Ổ cứng SSD', 'Ổ cứng di động'] },
  { name: 'Phụ kiện', children: ['Hub & Dock', 'Lót chuột'] },
];

export interface SeedProduct {
  category: string;
  sku: string;
  name: string;
  brand: string;
  /** Đơn vị: đồng. */
  price: number;
  compareAtPrice?: number;
  stock: number;
  featured?: boolean;
  attributes: Array<[string, string]>;
}

export const PRODUCTS: SeedProduct[] = [
  // ── Bàn phím cơ ───────────────────────────────────────────────────────
  {
    category: 'Bàn phím cơ',
    sku: 'KB-AKKO-3068B',
    name: 'Akko 3068B Plus World Tour Tokyo',
    brand: 'Akko',
    price: 1690000,
    compareAtPrice: 1990000,
    stock: 42,
    featured: true,
    attributes: [
      ['Kết nối', 'Bluetooth 5.0 / 2.4GHz / USB-C'],
      ['Switch', 'Akko CS Jelly Pink'],
      ['Layout', '68 phím'],
      ['Đèn nền', 'RGB'],
    ],
  },
  {
    category: 'Bàn phím cơ',
    sku: 'KB-KEYCH-K8',
    name: 'Keychron K8 Pro QMK/VIA',
    brand: 'Keychron',
    price: 2450000,
    stock: 18,
    attributes: [
      ['Kết nối', 'Bluetooth 5.1 / USB-C'],
      ['Switch', 'Gateron G Pro Brown'],
      ['Layout', 'TKL 87 phím'],
      ['Hot-swap', 'Có'],
    ],
  },
  {
    category: 'Bàn phím cơ',
    sku: 'KB-LEO-FC660',
    name: 'Leopold FC660M PD',
    brand: 'Leopold',
    price: 2890000,
    stock: 7,
    attributes: [
      ['Kết nối', 'USB-C tháo rời'],
      ['Switch', 'Cherry MX Silent Red'],
      ['Layout', '66 phím'],
      ['Keycap', 'PBT Double-shot'],
    ],
  },
  {
    category: 'Bàn phím cơ',
    sku: 'KB-DURG-K320',
    name: 'Durgod Taurus K320 Nebula',
    brand: 'Durgod',
    price: 1990000,
    stock: 0,
    attributes: [
      ['Kết nối', 'USB-C'],
      ['Switch', 'Cherry MX Blue'],
      ['Layout', 'TKL 87 phím'],
      ['Đèn nền', 'RGB'],
    ],
  },
  // ── Bàn phím không dây ────────────────────────────────────────────────
  {
    category: 'Bàn phím không dây',
    sku: 'KB-LOG-MXKEYS',
    name: 'Logitech MX Keys S',
    brand: 'Logitech',
    price: 2790000,
    compareAtPrice: 3190000,
    stock: 25,
    featured: true,
    attributes: [
      ['Kết nối', 'Bluetooth / Logi Bolt'],
      ['Pin', '10 ngày có đèn nền'],
      ['Layout', 'Full-size'],
      ['Đa thiết bị', '3 thiết bị'],
    ],
  },
  {
    category: 'Bàn phím không dây',
    sku: 'KB-LOG-K380',
    name: 'Logitech K380 Multi-Device',
    brand: 'Logitech',
    price: 690000,
    stock: 63,
    attributes: [
      ['Kết nối', 'Bluetooth 3.0'],
      ['Pin', 'AAA, 2 năm'],
      ['Layout', 'Mini'],
      ['Đa thiết bị', '3 thiết bị'],
    ],
  },
  {
    category: 'Bàn phím không dây',
    sku: 'KB-RAP-E9350',
    name: 'Rapoo E9350G Multi-mode',
    brand: 'Rapoo',
    price: 890000,
    stock: 31,
    attributes: [
      ['Kết nối', 'Bluetooth / 2.4GHz'],
      ['Độ dày', '5.6mm'],
      ['Layout', 'Full-size'],
    ],
  },
  // ── Chuột gaming ──────────────────────────────────────────────────────
  {
    category: 'Chuột gaming',
    sku: 'MS-LOG-GPXS2',
    name: 'Logitech G Pro X Superlight 2',
    brand: 'Logitech',
    price: 3290000,
    compareAtPrice: 3690000,
    stock: 15,
    featured: true,
    attributes: [
      ['Cảm biến', 'HERO 2 - 32000 DPI'],
      ['Trọng lượng', '60g'],
      ['Kết nối', 'Lightspeed không dây'],
      ['Pin', '95 giờ'],
    ],
  },
  {
    category: 'Chuột gaming',
    sku: 'MS-RAZ-VIPERV3',
    name: 'Razer Viper V3 Pro',
    brand: 'Razer',
    price: 3590000,
    stock: 9,
    attributes: [
      ['Cảm biến', 'Focus Pro 35K'],
      ['Trọng lượng', '54g'],
      ['Kết nối', 'HyperSpeed không dây'],
      ['Polling rate', '8000Hz'],
    ],
  },
  {
    category: 'Chuột gaming',
    sku: 'MS-STEEL-AER3',
    name: 'SteelSeries Aerox 3 Wireless',
    brand: 'SteelSeries',
    price: 1890000,
    stock: 22,
    attributes: [
      ['Cảm biến', 'TrueMove Air 18000 DPI'],
      ['Trọng lượng', '68g'],
      ['Kết nối', '2.4GHz / Bluetooth'],
      ['Chống nước', 'IP54'],
    ],
  },
  {
    category: 'Chuột gaming',
    sku: 'MS-PULS-X2MINI',
    name: 'Pulsar X2 Mini Wireless',
    brand: 'Pulsar',
    price: 2190000,
    stock: 4,
    attributes: [
      ['Cảm biến', 'PAW3395'],
      ['Trọng lượng', '52g'],
      ['Kết nối', '2.4GHz'],
      ['Switch', 'Kailh GM 8.0'],
    ],
  },
  // ── Chuột văn phòng ───────────────────────────────────────────────────
  {
    category: 'Chuột văn phòng',
    sku: 'MS-LOG-MXM3S',
    name: 'Logitech MX Master 3S',
    brand: 'Logitech',
    price: 2390000,
    compareAtPrice: 2690000,
    stock: 38,
    featured: true,
    attributes: [
      ['Cảm biến', '8000 DPI'],
      ['Kết nối', 'Bluetooth / Logi Bolt'],
      ['Click yên tĩnh', 'Có'],
      ['Pin', '70 ngày'],
    ],
  },
  {
    category: 'Chuột văn phòng',
    sku: 'MS-LOG-M331',
    name: 'Logitech M331 Silent Plus',
    brand: 'Logitech',
    price: 350000,
    stock: 87,
    attributes: [
      ['Cảm biến', '1000 DPI'],
      ['Kết nối', '2.4GHz USB'],
      ['Click yên tĩnh', 'Có'],
      ['Pin', 'AA, 24 tháng'],
    ],
  },
  {
    category: 'Chuột văn phòng',
    sku: 'MS-MICR-ARC',
    name: 'Microsoft Arc Mouse',
    brand: 'Microsoft',
    price: 1590000,
    stock: 12,
    attributes: [
      ['Kết nối', 'Bluetooth 4.0'],
      ['Thiết kế', 'Gập phẳng'],
      ['Cuộn', 'Cảm ứng toàn mặt'],
    ],
  },
  // ── Tai nghe chụp tai ─────────────────────────────────────────────────
  {
    category: 'Tai nghe chụp tai',
    sku: 'HP-SONY-XM5',
    name: 'Sony WH-1000XM5',
    brand: 'Sony',
    price: 7490000,
    compareAtPrice: 8490000,
    stock: 11,
    featured: true,
    attributes: [
      ['Chống ồn', 'Chủ động, 8 micro'],
      ['Pin', '30 giờ'],
      ['Codec', 'LDAC / AAC / SBC'],
      ['Sạc nhanh', '3 phút = 3 giờ'],
    ],
  },
  {
    category: 'Tai nghe chụp tai',
    sku: 'HP-BOSE-QC45',
    name: 'Bose QuietComfort 45',
    brand: 'Bose',
    price: 5990000,
    stock: 6,
    attributes: [
      ['Chống ồn', 'Chủ động'],
      ['Pin', '24 giờ'],
      ['Trọng lượng', '240g'],
    ],
  },
  {
    category: 'Tai nghe chụp tai',
    sku: 'HP-STEEL-NOVA7',
    name: 'SteelSeries Arctis Nova 7',
    brand: 'SteelSeries',
    price: 4290000,
    stock: 19,
    attributes: [
      ['Kết nối', '2.4GHz / Bluetooth đồng thời'],
      ['Pin', '38 giờ'],
      ['Micro', 'ClearCast Gen 2'],
      ['Driver', '40mm'],
    ],
  },
  {
    category: 'Tai nghe chụp tai',
    sku: 'HP-HYPER-CA2',
    name: 'HyperX Cloud Alpha 2',
    brand: 'HyperX',
    price: 2190000,
    stock: 27,
    attributes: [
      ['Kết nối', 'Jack 3.5mm'],
      ['Driver', 'Dual chamber 50mm'],
      ['Micro', 'Tháo rời, khử ồn'],
    ],
  },
  // ── Tai nghe nhét tai ─────────────────────────────────────────────────
  {
    category: 'Tai nghe nhét tai',
    sku: 'EP-APPL-APP2',
    name: 'Apple AirPods Pro 2 USB-C',
    brand: 'Apple',
    price: 5690000,
    stock: 33,
    featured: true,
    attributes: [
      ['Chống ồn', 'Chủ động thế hệ 2'],
      ['Pin', '6 giờ + 30 giờ hộp'],
      ['Chống nước', 'IP54'],
      ['Chip', 'H2'],
    ],
  },
  {
    category: 'Tai nghe nhét tai',
    sku: 'EP-SAM-BUDS3',
    name: 'Samsung Galaxy Buds3 Pro',
    brand: 'Samsung',
    price: 4290000,
    compareAtPrice: 4990000,
    stock: 21,
    attributes: [
      ['Chống ồn', 'Chủ động thích ứng'],
      ['Pin', '6 giờ'],
      ['Codec', 'SSC UHQ / AAC'],
      ['Chống nước', 'IP57'],
    ],
  },
  {
    category: 'Tai nghe nhét tai',
    sku: 'EP-SOUND-L4NC',
    name: 'Soundcore Liberty 4 NC',
    brand: 'Soundcore',
    price: 1990000,
    stock: 45,
    attributes: [
      ['Chống ồn', 'Adaptive ANC 2.0'],
      ['Pin', '10 giờ'],
      ['Codec', 'LDAC'],
      ['Chống nước', 'IPX4'],
    ],
  },
  // ── Màn hình gaming ───────────────────────────────────────────────────
  {
    category: 'Màn hình gaming',
    sku: 'MN-LG-27GP850',
    name: 'LG UltraGear 27GP850-B',
    brand: 'LG',
    price: 8990000,
    compareAtPrice: 10490000,
    stock: 8,
    featured: true,
    attributes: [
      ['Kích thước', '27 inch'],
      ['Độ phân giải', '2560x1440'],
      ['Tần số quét', '165Hz (OC 180Hz)'],
      ['Tấm nền', 'Nano IPS'],
      ['Phản hồi', '1ms GtG'],
    ],
  },
  {
    category: 'Màn hình gaming',
    sku: 'MN-SAM-G5-32',
    name: 'Samsung Odyssey G5 32 inch',
    brand: 'Samsung',
    price: 6790000,
    stock: 14,
    attributes: [
      ['Kích thước', '32 inch cong 1000R'],
      ['Độ phân giải', '2560x1440'],
      ['Tần số quét', '165Hz'],
      ['Tấm nền', 'VA'],
    ],
  },
  {
    category: 'Màn hình gaming',
    sku: 'MN-ASUS-VG249',
    name: 'ASUS TUF Gaming VG249Q1A',
    brand: 'ASUS',
    price: 3690000,
    stock: 26,
    attributes: [
      ['Kích thước', '23.8 inch'],
      ['Độ phân giải', '1920x1080'],
      ['Tần số quét', '165Hz'],
      ['Tấm nền', 'IPS'],
    ],
  },
  // ── Màn hình đồ hoạ ───────────────────────────────────────────────────
  {
    category: 'Màn hình đồ hoạ',
    sku: 'MN-DELL-U2723QE',
    name: 'Dell UltraSharp U2723QE',
    brand: 'Dell',
    price: 13990000,
    stock: 5,
    attributes: [
      ['Kích thước', '27 inch'],
      ['Độ phân giải', '3840x2160'],
      ['Màu', '98% DCI-P3'],
      ['Cổng', 'USB-C 90W, RJ45'],
    ],
  },
  {
    category: 'Màn hình đồ hoạ',
    sku: 'MN-BENQ-PD2705U',
    name: 'BenQ DesignVue PD2705U',
    brand: 'BenQ',
    price: 12490000,
    stock: 3,
    attributes: [
      ['Kích thước', '27 inch'],
      ['Độ phân giải', '3840x2160'],
      ['Màu', '99% sRGB, có Calibration Report'],
      ['Cổng', 'USB-C 65W'],
    ],
  },
  {
    category: 'Màn hình đồ hoạ',
    sku: 'MN-LG-32UN880',
    name: 'LG Ergo 32UN880-B',
    brand: 'LG',
    price: 11290000,
    stock: 0,
    attributes: [
      ['Kích thước', '31.5 inch'],
      ['Độ phân giải', '3840x2160'],
      ['Chân đế', 'Ergo kẹp bàn'],
      ['Màu', '95% DCI-P3'],
    ],
  },
  // ── Ổ cứng SSD ────────────────────────────────────────────────────────
  {
    category: 'Ổ cứng SSD',
    sku: 'SS-SAM-990P-1T',
    name: 'Samsung 990 PRO 1TB NVMe',
    brand: 'Samsung',
    price: 2790000,
    compareAtPrice: 3190000,
    stock: 34,
    featured: true,
    attributes: [
      ['Dung lượng', '1TB'],
      ['Chuẩn', 'M.2 NVMe PCIe 4.0'],
      ['Đọc tuần tự', '7450 MB/s'],
      ['Ghi tuần tự', '6900 MB/s'],
      ['Bảo hành', '5 năm'],
    ],
  },
  {
    category: 'Ổ cứng SSD',
    sku: 'SS-WD-SN850X-2T',
    name: 'WD Black SN850X 2TB',
    brand: 'Western Digital',
    price: 4690000,
    stock: 16,
    attributes: [
      ['Dung lượng', '2TB'],
      ['Chuẩn', 'M.2 NVMe PCIe 4.0'],
      ['Đọc tuần tự', '7300 MB/s'],
      ['Bảo hành', '5 năm'],
    ],
  },
  {
    category: 'Ổ cứng SSD',
    sku: 'SS-KING-NV2-500',
    name: 'Kingston NV2 500GB',
    brand: 'Kingston',
    price: 890000,
    stock: 58,
    attributes: [
      ['Dung lượng', '500GB'],
      ['Chuẩn', 'M.2 NVMe PCIe 4.0'],
      ['Đọc tuần tự', '3500 MB/s'],
      ['Bảo hành', '3 năm'],
    ],
  },
  // ── Ổ cứng di động ────────────────────────────────────────────────────
  {
    category: 'Ổ cứng di động',
    sku: 'PD-SAM-T7S-1T',
    name: 'Samsung T7 Shield 1TB',
    brand: 'Samsung',
    price: 2590000,
    stock: 20,
    attributes: [
      ['Dung lượng', '1TB'],
      ['Kết nối', 'USB 3.2 Gen 2'],
      ['Tốc độ', '1050 MB/s'],
      ['Chống nước', 'IP65'],
    ],
  },
  {
    category: 'Ổ cứng di động',
    sku: 'PD-SAND-EXT-2T',
    name: 'SanDisk Extreme Portable V2 2TB',
    brand: 'SanDisk',
    price: 4190000,
    stock: 9,
    attributes: [
      ['Dung lượng', '2TB'],
      ['Kết nối', 'USB-C 3.2 Gen 2'],
      ['Tốc độ', '1050 MB/s'],
      ['Chống nước', 'IP55'],
    ],
  },
  // ── Hub & Dock ────────────────────────────────────────────────────────
  {
    category: 'Hub & Dock',
    sku: 'HB-ANK-575',
    name: 'Anker 575 USB-C Docking Station 13-in-1',
    brand: 'Anker',
    price: 4990000,
    stock: 13,
    attributes: [
      ['Số cổng', '13'],
      ['Sạc laptop', '100W Power Delivery'],
      ['Màn hình ngoài', '2 x 4K@60Hz'],
      ['Mạng', 'RJ45 1Gbps'],
    ],
  },
  {
    category: 'Hub & Dock',
    sku: 'HB-UGR-7IN1',
    name: 'Ugreen 7-in-1 USB-C Hub',
    brand: 'Ugreen',
    price: 890000,
    compareAtPrice: 1090000,
    stock: 52,
    attributes: [
      ['Số cổng', '7'],
      ['HDMI', '4K@30Hz'],
      ['Sạc', '100W Pass-through'],
      ['Thẻ nhớ', 'SD / microSD'],
    ],
  },
  {
    category: 'Hub & Dock',
    sku: 'HB-BEL-4IN1',
    name: 'Belkin Connect USB-C 4-in-1',
    brand: 'Belkin',
    price: 1290000,
    stock: 24,
    attributes: [
      ['Số cổng', '4'],
      ['HDMI', '4K@60Hz'],
      ['Sạc', '100W Pass-through'],
    ],
  },
  // ── Lót chuột ─────────────────────────────────────────────────────────
  {
    category: 'Lót chuột',
    sku: 'MP-STEEL-QCK-XL',
    name: 'SteelSeries QcK Heavy XL',
    brand: 'SteelSeries',
    price: 690000,
    stock: 41,
    attributes: [
      ['Kích thước', '900 x 400 x 4mm'],
      ['Bề mặt', 'Vải dệt'],
      ['Đế', 'Cao su chống trượt'],
    ],
  },
  {
    category: 'Lót chuột',
    sku: 'MP-RAZ-GIGA-3XL',
    name: 'Razer Gigantus V2 3XL',
    brand: 'Razer',
    price: 990000,
    stock: 17,
    attributes: [
      ['Kích thước', '1200 x 550 x 4mm'],
      ['Bề mặt', 'Vải micro-weave'],
      ['Viền', 'May chống sờn'],
    ],
  },
  {
    category: 'Lót chuột',
    sku: 'MP-LOG-POWERPLAY',
    name: 'Logitech G Powerplay 2',
    brand: 'Logitech',
    price: 3490000,
    stock: 2,
    attributes: [
      ['Kích thước', '344 x 275mm'],
      ['Sạc không dây', 'Có, liên tục'],
      ['Bề mặt', 'Cứng + vải, thay được'],
    ],
  },
];

export const COUPONS = [
  {
    code: 'WELCOME10',
    description: 'Giảm 10% cho đơn đầu tiên, tối đa 100.000đ',
    type: 'PERCENT' as const,
    value: 10,
    minOrderAmount: 200000,
    maxDiscountAmount: 100000,
    usageLimit: 1000,
    perUserLimit: 1,
    daysValid: 90,
  },
  {
    code: 'FREESHIP',
    description: 'Miễn phí vận chuyển cho đơn từ 300.000đ',
    type: 'FIXED' as const,
    value: 30000,
    minOrderAmount: 300000,
    maxDiscountAmount: null,
    usageLimit: null,
    perUserLimit: 5,
    daysValid: 60,
  },
  {
    code: 'SALE50K',
    description: 'Giảm ngay 50.000đ cho đơn từ 500.000đ',
    type: 'FIXED' as const,
    value: 50000,
    minOrderAmount: 500000,
    maxDiscountAmount: null,
    usageLimit: 500,
    perUserLimit: 2,
    daysValid: 30,
  },
  {
    code: 'TECH15',
    description: 'Giảm 15% toàn ngành hàng, tối đa 300.000đ',
    type: 'PERCENT' as const,
    value: 15,
    minOrderAmount: 1000000,
    maxDiscountAmount: 300000,
    usageLimit: 200,
    perUserLimit: 1,
    daysValid: 14,
  },
  {
    code: 'EXPIRED10',
    description: 'Mã đã hết hạn — dùng để kiểm thử luồng từ chối',
    type: 'PERCENT' as const,
    value: 10,
    minOrderAmount: 0,
    maxDiscountAmount: null,
    usageLimit: null,
    perUserLimit: 1,
    daysValid: -5,
  },
];
